### ISSUE TITLE
IntelliJBehave Not Allowing Click-through in .story files 

### ISSUE THREAD

**Issue by erivas39** [kumaraman21/IntelliJBehave#13]
Opened IntelliJ for first time on an Ubuntu box, setup and associated story files with text files, etc.  Story highlights work, however in my .story files, none of the lines change to blue-highlighted nor underlined after CTRL+left-click.
Verison of IntelliJ is 10.5.1

-Everic: QA-SWA FantasticFour (PODIV)

Stack trace below:

null
java.lang.NullPointerException
    at com.github.kumaraman21.intellijbehave.resolver.DeclaredAnnotationSet.<init>(DeclaredAnnotationSet.java:48)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference$StepAnnotationFinder.processFile(StepPsiReference.java:89)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:31)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:71)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:60)
    at com.github.kumaraman21.intellijbehave.codeInspector.UndefinedStepsInspection$1.visitElement(UndefinedStepsInspection.java:72)
    at com.intellij.extapi.psi.PsiElementBase.accept(PsiElementBase.java:144)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:334)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:289)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:257)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:241)
    at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:116)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:114)
    at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:241)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:188)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

java.lang.NullPointerException
    at com.github.kumaraman21.intellijbehave.resolver.DeclaredAnnotationSet.<init>(DeclaredAnnotationSet.java:48)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference$StepAnnotationFinder.processFile(StepPsiReference.java:89)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:31)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:71)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:60)
    at com.github.kumaraman21.intellijbehave.codeInspector.UndefinedStepsInspection$1.visitElement(UndefinedStepsInspection.java:72)
    at com.intellij.extapi.psi.PsiElementBase.accept(PsiElementBase.java:144)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:334)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:289)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:257)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:241)
    at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:116)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:114)
    at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:241)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:188)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

java.lang.NullPointerException
    at com.github.kumaraman21.intellijbehave.resolver.DeclaredAnnotationSet.<init>(DeclaredAnnotationSet.java:48)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference$StepAnnotationFinder.processFile(StepPsiReference.java:89)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:31)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:36)
    at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:71)
    at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:60)
    at com.github.kumaraman21.intellijbehave.codeInspector.UndefinedStepsInspection$1.visitElement(UndefinedStepsInspection.java:72)
    at com.intellij.extapi.psi.PsiElementBase.accept(PsiElementBase.java:144)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:334)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:289)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:74)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:257)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$1.process(LocalInspectionsPass.java:241)
    at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:116)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:114)
    at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:241)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:225)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at com.intellij.concurrency.JobImpl.scheduleAndWaitForResults(JobImpl.java:133)
    at com.intellij.concurrency.JobUtil.a(JobUtil.java:71)
    at com.intellij.concurrency.JobUtil.invokeConcurrentlyUnderProgress(JobUtil.java:111)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:327)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:188)
    at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:57)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:58)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:348)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1013)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:340)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:209)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:338)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:314)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:133)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:130)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

**Comment by erivas39** [comment]
Not a bug.  I had not compiled yet on my new machine.  However, after I changed the default setting for Maven User settings to /opt/maven2/conf/settings.xml, I was able to click-through to the steps file from Story file.
