### ISSUE TITLE
Exception when parsing story file

### ISSUE THREAD

**Issue by gphilipp** [kumaraman21/IntelliJBehave#14]
Tokens [STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, WHITE_SPACE] were not inserted into the tree. Text:
Meta:

Narrative:
As a gardener
I want to mow the lawn
So that I can keep my garden tidy

Scenario: go north
Given a mower in 0,0 and oriented to the north
When I orient the mower to the north
And I move the mower
Then the mower should be in 0,1 facing north

Scenario: pivot left and move
Given a mower in 1,2 and oriented to the north
When I pivot the mower to the left
And I move the mower
Then the mower should be in 0,2 facing west

Scenario: first expectation given by client
Given a mower in 1,2 and oriented to the north
When I pivot the mower to the left
And I move the mower
When I pivot the mower to the left
And I move the mower
When I pivot the mower to the left
And I move the mower
When I pivot the mower to the left
And I move the mower
And I move the mower
Then the mower should be in 1,3 facing north

Scenario: second expectation given by client
Given a mower in 1,2 and oriented to the north
When I move the mower
And I move the mower
When I pivot the mower to the right
And I move the mower
And I move the mower
 I pivot the mower to the right
And I move the mower
Then the mower should be in 1,3 facing north

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1103)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1108)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1103)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1108)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1103)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1108)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1103)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1108)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:978)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:962)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:63)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:286)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:231)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:205)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:144)
    at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:82)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:544)
    at com.intellij.psi.impl.DocumentCommitThread.access$600(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:433)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1040)
    at com.intellij.psi.impl.DocumentCommitThread.b(DocumentCommitThread.java:446)
    at com.intellij.psi.impl.DocumentCommitThread.access$500(DocumentCommitThread.java:69)
    at com.intellij.psi.impl.DocumentCommitThread$1.run(DocumentCommitThread.java:400)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:206)
    at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:397)
    at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:305)
    at java.lang.Thread.run(Thread.java:662)

**Comment by bearfoot** [comment]
Hello, I experienced the same issue :-(

Tokens [TABLE_ROW, TABLE_ROW, TABLE_ROW, TABLE_ROW, TABLE_ROW, WHITE_SPACE] were not inserted into the tree. Language: Story, Text:

Scenario: scenario description

Given current group is <configuration_name> root group

Then current group has <documents_nb> documents with valid uri
And current group has <subgroups_nb> subgroups with valid uris
And current group has current configuration root group id
And current group has current configuration root group uri
And current group has a valid uri

Examples:
|configuration_name|documents_nb|subgroups_nb|

|default|4|3|
|ellipse|4|3|
|visited-templates|4|3|
|notification|4|3|

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1110)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:983)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:967)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:160)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:204)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:32)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:44)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:757)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:414)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:371)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.a(CollectHighlightsUtil.java:157)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.findCommonParent(CollectHighlightsUtil.java:138)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:57)
    at com.intellij.codeInsight.daemon.impl.CollectHighlightsUtil.getElementsInRange(CollectHighlightsUtil.java:49)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:63)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:350)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1053)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:342)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:218)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:340)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:316)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:134)
    at com.intellij.concurrency.JobUtil$3.call(JobUtil.java:131)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
