### ISSUE TITLE
Exception when editing

### ISSUE THREAD

**Issue by bodiam** [kumaraman21/IntelliJBehave#20]
Hi Kumaraman, thanks for the great work on the plugin, but I sometimes get errors, and I thought, let's make an issue for this. I hope you can fix it!

Kind regards, Erik Pragt

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1108)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:980)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:965)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:164)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:208)
    at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:164)
    at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:48)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:79)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:170)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:579)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:572)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6$2.run(PsiSearchHelperImpl.java:241)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.process(PsiSearchHelperImpl.java:222)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.process(PsiSearchHelperImpl.java:211)
    at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:231)
    at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
    at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1113)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:980)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:965)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:39)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:164)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:208)
    at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:164)
    at com.intellij.psi.impl.source.tree.CompositeElement.findLeafElementAt(CompositeElement.java:48)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:79)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:170)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:579)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$13.process(PsiSearchHelperImpl.java:572)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6$2.run(PsiSearchHelperImpl.java:241)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.process(PsiSearchHelperImpl.java:222)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$6.process(PsiSearchHelperImpl.java:211)
    at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:231)
    at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
    at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
    at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
    at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)

**Comment by AndreeaCh** [comment]
Hi,

This usually happens when you start a scenario with an "And" step, because there is no previous step and the StoryParser is not able to set the step type.

Best Regards,
Andreea Ch

**Comment by bodiam** [comment]
Really, no idea. This is issue is 10 months old, so I have no ideas what I was doing here anymore. Thanks for the reply though!
