### ISSUE TITLE
NPE in DeclaredAnnotationSet

### ISSUE THREAD

**Issue by gclayburg** [kumaraman21/IntelliJBehave#22]
I'm getting this NPE error while performing basic tasks with stores when this plugin is enabled:

2012-10-21 11:06:59,885 [2563138]  ERROR - currency.PrioritizedFutureTask - IntelliJ IDEA 11.1.3  Build #IU-117.798
2012-10-21 11:06:59,885 [2563138]  ERROR - currency.PrioritizedFutureTask - JDK: 1.7.0_05
2012-10-21 11:06:59,885 [2563138]  ERROR - currency.PrioritizedFutureTask - VM: Java HotSpot(TM) 64-Bit Server VM
2012-10-21 11:06:59,885 [2563138]  ERROR - currency.PrioritizedFutureTask - Vendor: Oracle Corporation
2012-10-21 11:06:59,885 [2563138]  ERROR - currency.PrioritizedFutureTask - OS: Windows 7
2012-10-21 11:06:59,886 [2563139]  ERROR - currency.PrioritizedFutureTask - Original exception:
java.lang.NullPointerException
        at com.github.kumaraman21.intellijbehave.resolver.DeclaredAnnotationSet.<init>(DeclaredAnnotationSet.java:48)
        at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference$StepAnnotationFinder.processFile(StepPsiReference.java:89)
        at com.intellij.openapi.roots.impl.FileIndexImplUtil$1.visitFile(FileIndexImplUtil.java:38)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:170)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:182)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:162)
        at com.intellij.openapi.roots.impl.FileIndexImplUtil.iterateRecursively(FileIndexImplUtil.java:33)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:71)
        at com.github.kumaraman21.intellijbehave.resolver.StepPsiReference.resolve(StepPsiReference.java:60)
        at com.github.kumaraman21.intellijbehave.codeInspector.UnusedStepsInspection$1.visitElement(UnusedStepsInspection.java:101)
        at com.intellij.psi.JavaElementVisitor.visitAnnotation(JavaElementVisitor.java:340)
        at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.accept(PsiAnnotationImpl.java:111)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:403)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:361)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$100(LocalInspectionsPass.java:76)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:327)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:309)
        at com.intellij.concurrency.JobUtil$2$1.run(JobUtil.java:117)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:218)
        at com.intellij.concurrency.JobUtil$2.process(JobUtil.java:115)
        at com.intellij.concurrency.JobUtil$1.run(JobUtil.java:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
        at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1053)
        at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

**Comment by gclayburg** [comment]
FYI - this occurs when simply opening a very basic Steps class
