### ISSUE TITLE
Issues in Parsing Table - Tokens [TABLE_ROW, TABLE_ROW, WHITE_SPACE] were not inserted into the tree.

### ISSUE THREAD

**Issue by ppand** [kumaraman21/IntelliJBehave#25]
Tokens [TABLE_ROW, TABLE_ROW, WHITE_SPACE] were not inserted into the tree. Language: Story, Text:

Scenario: [1] Book Position

Given  following prices:
|epic               |underlying |ask  |bid  |mid |
|KA.D.VOD.DAILY.IP  |KA.D.VOD   |1180 |1170 |1175|

And following markets:
|epic               |currency|
|KA.D.VOD.DAILY.IP  |GBP     |

And following <siteType> accounts:
|accountId |balance |currency |
|A         |100000  |GBP      |

!-- Submit a order

When client submits following OTC orders:
|accountId |direction |orderId    |size |level |currency |market            |
|A         |sell      |orderId |25   |1170  |GBP      |KA.D.VOD.DAILY.IP|

Then client should receive following confirms for order:
|accountId |size |level |currency |epic               |action|
|A         |25   |1170  |GBP      |KA.D.VOD.DAILY.IP |ACCEPT|

When AFS subscribes following accounts A

When xds provides these fids for the epic KA.D.VOD.DAILY.IP:
|prompt          |bid   |ask   |mid  |
|mkcommod  DEC27 |22223 |22223 |22223|

Then 1 account figures should be received for account A

Examples:
|siteType|
|B       |

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
    at com.intellij.lang.impl.PsiBuilderImpl.d(PsiBuilderImpl.java:1109)
    at com.intellij.lang.impl.PsiBuilderImpl.c(PsiBuilderImpl.java:982)
    at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:967)
    at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
    at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
    at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.e(LazyParseableElement.java:165)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:209)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:34)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:44)
    at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:778)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:441)
    at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:427)
    at com.intellij.psi.impl.source.PsiFileImpl.findElementAt(PsiFileImpl.java:579)
    at com.intellij.ide.browsers.actions.BaseWebBrowserAction.getElement(BaseWebBrowserAction.java:109)
    at com.intellij.ide.browsers.actions.BaseWebBrowserAction.update(BaseWebBrowserAction.java:77)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:98)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:165)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:124)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:84)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:144)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.run(ActionToolbarImpl.java:887)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:465)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:1909)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:443)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:933)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$300(ActionToolbarImpl.java:63)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$4.run(ActionToolbarImpl.java:959)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:727)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.awt.EventQueue$3.run(EventQueue.java:686)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:697)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:673)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:498)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:333)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by yujunliang** [comment]
Hi Aman,

How are you?

Good job on developing a jBehave plugin.

I have this problem in our project as well? Do you have time to fix it?

Thank you.

**Comment by sergejs-cerepanovs-akqa** [comment]
same here. Any news on that?
Maybe there is a workaround, on how to still use example tables?
Thanks in advance!

**Comment by akshattambe** [comment]
is anyone through this error ??
