### ISSUE TITLE
NPE in Settings panel in IDEA 12

### ISSUE THREAD

**Issue by proshin-roman** [kumaraman21/IntelliJBehave#31]
I have the next exception when trying to open settings panel of this plugin in IDEA 12.1.7 Ultimate:

```
null
java.lang.NullPointerException
    at com.github.kumaraman21.intellijbehave.settings.JBehaveSettingsPanel.<init>(JBehaveSettingsPanel.java:47)
    at com.github.kumaraman21.intellijbehave.settings.JBehaveConfigurable.createComponent(JBehaveConfigurable.java:53)
    at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1270)
    at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:455)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:68)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:424)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1130)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:418)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:416)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
```

I will be glad to help with any questions. Thanks for your work!

**Comment by vase4kin** [comment]
Try to use "JBehave Support" plugin, it fixes many of original plugin issues.

**Comment by proshin-roman** [comment]
This is what I'm using now and it has the described problem :confused:
