### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by olenapavlenko** [kumaraman21/IntelliJBehave#40]
IntellijBehave permanently fails

Error message: " Tokens [TABLE_ROW, TABLE_ROW, TABLE_ROW, TABLE_ROW, SCENARIO_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, SCENARIO_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, SCENARIO_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT, STEP_TYPE, STEP_TEXT] were not inserted into the tree. Language: Story, Text:"

at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1052)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:906)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:901)
	at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:51)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:814)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:122)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:72)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideAllRoots(Divider.java:59)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.collectInformationWithProgress(InjectedGeneralHighlightingPass.java:86)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by nikolaus07** [comment]
- I have the same bug on Linux with Intellij.  On windows with intelliJ I have never this bug.
- And on linux and intelliJ it happens only, when I try to write comment. Starting with '!--'


java.lang.Throwable: Tokens [STEP_TYPE, STEP_TEXT, WHITE_SPACE] were not inserted into the tree. Language: Story, Text:
Narrative: Google Web Toolkit - Showcase

Scenario: Test the Toolkit itself
Given Web Browser is: 'Firefox'.
When Navigate to: 'http://samples.gwtproject.org/samples/Showcase/Showcase.html#!CwCheckBox'

!--  comment text     *** THIS IS CORRECT COMMENT ****
When Set Checkbox 'Tuesday' to '1'.

Scenario: close browser
!                   *** IN THIS LINE I AM NOT ABLE TO TYPE ANYTHING after typing !--  ****                       
When Close browser after running all GUI-stories.

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1081)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:929)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:924)
	at com.github.kumaraman21.intellijbehave.parser.StoryParser.parse(StoryParser.java:36)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:198)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:197)
